[project]
name = "gamma-hub-coordinator"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/gamma-hub-coordinator/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.gamma-hub-coordinator]
path = "contracts/gamma-hub-coordinator.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
